"""Blocks of the Blockdle (generated from minecraft-data 1.21.1; versions curated by hand).

id, name, tool to mine it, hardness (-1 = unbreakable), blast resistance, transparent, craftable
(on a crafting table), version it was added in (see VERSIONS).
"""
from __future__ import annotations

VERSIONS = ("Classic", "Indev–Beta", "1.0", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11",
            "1.12", "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21")

BLOCKS: tuple[tuple[str, str, str, float, float, bool, bool, str], ...] = (
    ('stone', 'Stone', 'Pickaxe', 1.5, 6.0, False, False, 'Classic'),
    ('granite', 'Granite', 'Pickaxe', 1.5, 6.0, False, True, '1.8'),
    ('diorite', 'Diorite', 'Pickaxe', 1.5, 6.0, False, True, '1.8'),
    ('andesite', 'Andesite', 'Pickaxe', 1.5, 6.0, False, True, '1.8'),
    ('deepslate', 'Deepslate', 'Pickaxe', 3.0, 6.0, False, False, '1.17'),
    ('tuff', 'Tuff', 'Pickaxe', 1.5, 6.0, False, False, '1.17'),
    ('calcite', 'Calcite', 'Pickaxe', 0.75, 0.75, False, False, '1.17'),
    ('dripstone_block', 'Dripstone Block', 'Pickaxe', 1.5, 1.0, False, True, '1.17'),
    ('grass_block', 'Grass Block', 'Shovel', 0.6, 0.6, False, False, 'Classic'),
    ('dirt', 'Dirt', 'Shovel', 0.5, 0.5, False, False, 'Classic'),
    ('coarse_dirt', 'Coarse Dirt', 'Shovel', 0.5, 0.5, False, True, '1.8'),
    ('podzol', 'Podzol', 'Shovel', 0.5, 0.5, False, False, '1.7'),
    ('mycelium', 'Mycelium', 'Shovel', 0.6, 0.6, False, False, '1.0'),
    ('mud', 'Mud', 'Shovel', 0.5, 0.5, False, False, '1.19'),
    ('clay', 'Clay', 'Shovel', 0.6, 0.6, False, True, 'Indev–Beta'),
    ('gravel', 'Gravel', 'Shovel', 0.6, 0.6, False, False, 'Classic'),
    ('sand', 'Sand', 'Shovel', 0.5, 0.5, False, False, 'Classic'),
    ('red_sand', 'Red Sand', 'Shovel', 0.5, 0.5, False, False, '1.7'),
    ('sandstone', 'Sandstone', 'Pickaxe', 0.8, 0.8, False, True, 'Indev–Beta'),
    ('red_sandstone', 'Red Sandstone', 'Pickaxe', 0.8, 0.8, False, True, '1.8'),
    ('ice', 'Ice', 'Pickaxe', 0.5, 0.5, True, False, 'Indev–Beta'),
    ('packed_ice', 'Packed Ice', 'Pickaxe', 0.5, 0.5, False, True, '1.7'),
    ('blue_ice', 'Blue Ice', 'Pickaxe', 2.8, 2.8, False, True, '1.13'),
    ('snow_block', 'Snow Block', 'Shovel', 0.2, 0.2, False, True, 'Indev–Beta'),
    ('powder_snow', 'Powder Snow', 'Any', 0.25, 0.25, False, False, '1.17'),
    ('obsidian', 'Obsidian', 'Pickaxe', 50.0, 1200.0, False, False, 'Classic'),
    ('crying_obsidian', 'Crying Obsidian', 'Pickaxe', 50.0, 1200.0, False, False, '1.16'),
    ('bedrock', 'Bedrock', 'None', -1.0, 3600000.0, False, False, 'Classic'),
    ('netherrack', 'Netherrack', 'Pickaxe', 0.4, 0.4, False, False, 'Indev–Beta'),
    ('soul_sand', 'Soul Sand', 'Shovel', 0.5, 0.5, False, False, 'Indev–Beta'),
    ('soul_soil', 'Soul Soil', 'Shovel', 0.5, 0.5, False, False, '1.16'),
    ('basalt', 'Basalt', 'Pickaxe', 1.25, 4.2, False, False, '1.16'),
    ('blackstone', 'Blackstone', 'Pickaxe', 1.5, 6.0, False, False, '1.16'),
    ('magma_block', 'Magma Block', 'Pickaxe', 0.5, 0.5, False, True, '1.10'),
    ('glowstone', 'Glowstone', 'Any', 0.3, 0.3, False, True, 'Indev–Beta'),
    ('end_stone', 'End Stone', 'Pickaxe', 3.0, 9.0, False, False, '1.0'),
    ('moss_block', 'Moss Block', 'Hoe', 0.1, 0.1, False, False, '1.17'),
    ('amethyst_block', 'Block of Amethyst', 'Pickaxe', 1.5, 1.5, False, True, '1.17'),
    ('budding_amethyst', 'Budding Amethyst', 'Pickaxe', 1.5, 1.5, False, False, '1.17'),
    ('sculk', 'Sculk', 'Hoe', 0.2, 0.2, False, False, '1.19'),
    ('sculk_sensor', 'Sculk Sensor', 'Hoe', 1.5, 1.5, False, False, '1.17'),
    ('sculk_shrieker', 'Sculk Shrieker', 'Hoe', 3.0, 3.0, False, False, '1.19'),
    ('sculk_catalyst', 'Sculk Catalyst', 'Hoe', 3.0, 3.0, False, False, '1.19'),
    ('sponge', 'Sponge', 'Hoe', 0.6, 0.6, False, False, 'Classic'),
    ('wet_sponge', 'Wet Sponge', 'Hoe', 0.6, 0.6, False, False, '1.8'),
    ('cobblestone', 'Cobblestone', 'Pickaxe', 2.0, 6.0, False, False, 'Classic'),
    ('mossy_cobblestone', 'Mossy Cobblestone', 'Pickaxe', 2.0, 6.0, False, True, 'Classic'),
    ('coal_ore', 'Coal Ore', 'Pickaxe', 3.0, 3.0, False, False, 'Classic'),
    ('iron_ore', 'Iron Ore', 'Pickaxe', 3.0, 3.0, False, False, 'Classic'),
    ('copper_ore', 'Copper Ore', 'Pickaxe', 3.0, 3.0, False, False, '1.17'),
    ('gold_ore', 'Gold Ore', 'Pickaxe', 3.0, 3.0, False, False, 'Classic'),
    ('redstone_ore', 'Redstone Ore', 'Pickaxe', 3.0, 3.0, False, False, 'Indev–Beta'),
    ('lapis_ore', 'Lapis Lazuli Ore', 'Pickaxe', 3.0, 3.0, False, False, 'Indev–Beta'),
    ('diamond_ore', 'Diamond Ore', 'Pickaxe', 3.0, 3.0, False, False, 'Indev–Beta'),
    ('emerald_ore', 'Emerald Ore', 'Pickaxe', 3.0, 3.0, False, False, '1.3'),
    ('deepslate_diamond_ore', 'Deepslate Diamond Ore', 'Pickaxe', 4.5, 3.0, False, False, '1.17'),
    ('nether_gold_ore', 'Nether Gold Ore', 'Pickaxe', 3.0, 3.0, False, False, '1.16'),
    ('nether_quartz_ore', 'Nether Quartz Ore', 'Pickaxe', 3.0, 3.0, False, False, '1.5'),
    ('ancient_debris', 'Ancient Debris', 'Pickaxe', 30.0, 1200.0, False, False, '1.16'),
    ('coal_block', 'Block of Coal', 'Pickaxe', 5.0, 6.0, False, True, '1.6'),
    ('iron_block', 'Block of Iron', 'Pickaxe', 5.0, 6.0, False, True, 'Classic'),
    ('copper_block', 'Block of Copper', 'Pickaxe', 3.0, 6.0, False, True, '1.17'),
    ('gold_block', 'Block of Gold', 'Pickaxe', 3.0, 6.0, False, True, 'Classic'),
    ('redstone_block', 'Block of Redstone', 'Pickaxe', 5.0, 6.0, False, True, '1.5'),
    ('lapis_block', 'Block of Lapis Lazuli', 'Pickaxe', 3.0, 3.0, False, True, 'Indev–Beta'),
    ('diamond_block', 'Block of Diamond', 'Pickaxe', 5.0, 6.0, False, True, 'Indev–Beta'),
    ('emerald_block', 'Block of Emerald', 'Pickaxe', 5.0, 6.0, False, True, '1.3'),
    ('netherite_block', 'Block of Netherite', 'Pickaxe', 50.0, 1200.0, False, True, '1.16'),
    ('quartz_block', 'Block of Quartz', 'Pickaxe', 0.8, 0.8, False, True, '1.5'),
    ('raw_iron_block', 'Block of Raw Iron', 'Pickaxe', 5.0, 6.0, False, True, '1.17'),
    ('oak_log', 'Oak Log', 'Axe', 2.0, 2.0, False, False, 'Classic'),
    ('oak_planks', 'Oak Planks', 'Axe', 2.0, 3.0, False, True, 'Classic'),
    ('oak_leaves', 'Oak Leaves', 'Hoe', 0.2, 0.2, True, False, 'Classic'),
    ('bamboo_block', 'Block of Bamboo', 'Axe', 2.0, 2.0, False, True, '1.20'),
    ('crimson_stem', 'Crimson Stem', 'Axe', 2.0, 2.0, False, False, '1.16'),
    ('nether_wart_block', 'Nether Wart Block', 'Hoe', 1.0, 1.0, False, True, '1.10'),
    ('mangrove_roots', 'Mangrove Roots', 'Axe', 0.7, 0.7, True, False, '1.19'),
    ('red_mushroom_block', 'Red Mushroom Block', 'Axe', 0.2, 0.2, False, False, 'Indev–Beta'),
    ('cactus', 'Cactus', 'Any', 0.4, 0.4, False, False, 'Indev–Beta'),
    ('sugar_cane', 'Sugar Cane', 'Axe', 0.0, 0.0, True, False, 'Indev–Beta'),
    ('pumpkin', 'Pumpkin', 'Axe', 1.0, 1.0, False, False, 'Indev–Beta'),
    ('carved_pumpkin', 'Carved Pumpkin', 'Axe', 1.0, 1.0, False, False, '1.13'),
    ('jack_o_lantern', "Jack o'Lantern", 'Axe', 1.0, 1.0, False, True, 'Indev–Beta'),
    ('melon', 'Melon', 'Axe', 1.0, 1.0, False, True, 'Indev–Beta'),
    ('hay_block', 'Hay Bale', 'Hoe', 0.5, 0.5, False, True, '1.6'),
    ('dried_kelp_block', 'Dried Kelp Block', 'Hoe', 0.5, 2.5, False, True, '1.13'),
    ('bamboo', 'Bamboo', 'Axe', 1.0, 1.0, True, False, '1.14'),
    ('vine', 'Vines', 'Axe', 0.2, 0.2, True, False, 'Indev–Beta'),
    ('lily_pad', 'Lily Pad', 'Axe', 0.0, 0.0, True, False, '1.0'),
    ('sweet_berry_bush', 'Sweet Berry Bush', 'Axe', 0.0, 0.0, True, False, '1.14'),
    ('cobweb', 'Cobweb', 'Sword', 4.0, 4.0, True, False, 'Indev–Beta'),
    ('oak_sapling', 'Oak Sapling', 'Axe', 0.0, 0.0, True, False, 'Classic'),
    ('dandelion', 'Dandelion', 'Any', 0.0, 0.0, True, False, 'Classic'),
    ('poppy', 'Poppy', 'Any', 0.0, 0.0, True, False, 'Classic'),
    ('sunflower', 'Sunflower', 'Any', 0.0, 0.0, True, False, '1.7'),
    ('brown_mushroom', 'Brown Mushroom', 'Axe', 0.0, 0.0, True, False, 'Classic'),
    ('bricks', 'Bricks', 'Pickaxe', 2.0, 6.0, False, True, 'Classic'),
    ('stone_bricks', 'Stone Bricks', 'Pickaxe', 1.5, 6.0, False, True, 'Indev–Beta'),
    ('mossy_stone_bricks', 'Mossy Stone Bricks', 'Pickaxe', 1.5, 6.0, False, True, 'Indev–Beta'),
    ('nether_bricks', 'Nether Bricks', 'Pickaxe', 2.0, 6.0, False, True, '1.0'),
    ('red_nether_bricks', 'Red Nether Bricks', 'Pickaxe', 2.0, 6.0, False, True, '1.10'),
    ('prismarine', 'Prismarine', 'Pickaxe', 1.5, 6.0, False, True, '1.8'),
    ('sea_lantern', 'Sea Lantern', 'Any', 0.3, 0.3, False, True, '1.8'),
    ('purpur_block', 'Purpur Block', 'Pickaxe', 1.5, 6.0, False, True, '1.9'),
    ('end_stone_bricks', 'End Stone Bricks', 'Pickaxe', 3.0, 9.0, False, True, '1.9'),
    ('terracotta', 'Terracotta', 'Pickaxe', 1.25, 4.2, False, False, '1.6'),
    ('white_concrete', 'White Concrete', 'Pickaxe', 1.8, 1.8, False, False, '1.12'),
    ('white_concrete_powder', 'White Concrete Powder', 'Shovel', 0.5, 0.5, False, True, '1.12'),
    ('white_glazed_terracotta', 'White Glazed Terracotta', 'Pickaxe', 1.4, 1.4, False, False, '1.12'),
    ('glass', 'Glass', 'Any', 0.3, 0.3, True, False, 'Classic'),
    ('white_stained_glass', 'White Stained Glass', 'Any', 0.3, 0.3, True, True, '1.7'),
    ('tinted_glass', 'Tinted Glass', 'Any', 0.3, 0.3, True, True, '1.17'),
    ('white_wool', 'White Wool', 'Shears', 0.8, 0.8, False, True, 'Classic'),
    ('white_carpet', 'White Carpet', 'Any', 0.1, 0.1, False, True, '1.6'),
    ('bookshelf', 'Bookshelf', 'Axe', 1.5, 1.5, False, True, 'Classic'),
    ('chiseled_bookshelf', 'Chiseled Bookshelf', 'Axe', 1.5, 1.5, False, True, '1.20'),
    ('mud_bricks', 'Mud Bricks', 'Pickaxe', 1.5, 3.0, False, True, '1.19'),
    ('honey_block', 'Honey Block', 'Any', 0.0, 0.0, True, True, '1.15'),
    ('honeycomb_block', 'Honeycomb Block', 'Any', 0.6, 0.6, False, True, '1.15'),
    ('slime_block', 'Slime Block', 'Any', 0.0, 0.0, True, True, '1.8'),
    ('bone_block', 'Bone Block', 'Pickaxe', 2.0, 2.0, False, True, '1.10'),
    ('target', 'Target', 'Hoe', 0.5, 0.5, False, True, '1.16'),
    ('shroomlight', 'Shroomlight', 'Hoe', 1.0, 1.0, False, False, '1.16'),
    ('ochre_froglight', 'Ochre Froglight', 'Any', 0.3, 0.3, False, False, '1.19'),
    ('crafting_table', 'Crafting Table', 'Axe', 2.5, 2.5, False, True, 'Indev–Beta'),
    ('furnace', 'Furnace', 'Pickaxe', 3.5, 3.5, False, True, 'Indev–Beta'),
    ('blast_furnace', 'Blast Furnace', 'Pickaxe', 3.5, 3.5, False, True, '1.14'),
    ('smoker', 'Smoker', 'Pickaxe', 3.5, 3.5, False, True, '1.14'),
    ('chest', 'Chest', 'Axe', 2.5, 2.5, False, True, 'Indev–Beta'),
    ('ender_chest', 'Ender Chest', 'Pickaxe', 22.5, 600.0, False, True, '1.3'),
    ('barrel', 'Barrel', 'Axe', 2.5, 2.5, False, True, '1.14'),
    ('enchanting_table', 'Enchanting Table', 'Pickaxe', 5.0, 1200.0, False, True, '1.0'),
    ('anvil', 'Anvil', 'Pickaxe', 5.0, 1200.0, False, True, '1.4'),
    ('grindstone', 'Grindstone', 'Pickaxe', 2.0, 6.0, False, True, '1.14'),
    ('smithing_table', 'Smithing Table', 'Axe', 2.5, 2.5, False, True, '1.14'),
    ('stonecutter', 'Stonecutter', 'Pickaxe', 3.5, 3.5, False, True, '1.14'),
    ('loom', 'Loom', 'Axe', 2.5, 2.5, False, True, '1.14'),
    ('cartography_table', 'Cartography Table', 'Axe', 2.5, 2.5, False, True, '1.14'),
    ('fletching_table', 'Fletching Table', 'Axe', 2.5, 2.5, False, True, '1.14'),
    ('brewing_stand', 'Brewing Stand', 'Pickaxe', 0.5, 0.5, True, True, '1.0'),
    ('cauldron', 'Cauldron', 'Pickaxe', 2.0, 2.0, True, True, '1.0'),
    ('composter', 'Composter', 'Axe', 0.6, 0.6, False, True, '1.14'),
    ('beacon', 'Beacon', 'Any', 3.0, 3.0, True, True, '1.4'),
    ('conduit', 'Conduit', 'Pickaxe', 3.0, 3.0, True, True, '1.13'),
    ('lodestone', 'Lodestone', 'Pickaxe', 3.5, 3.5, False, True, '1.16'),
    ('respawn_anchor', 'Respawn Anchor', 'Pickaxe', 50.0, 1200.0, False, True, '1.16'),
    ('bell', 'Bell', 'Pickaxe', 5.0, 5.0, False, False, '1.14'),
    ('lantern', 'Lantern', 'Pickaxe', 3.5, 3.5, True, True, '1.14'),
    ('torch', 'Torch', 'Any', 0.0, 0.0, True, True, 'Indev–Beta'),
    ('campfire', 'Campfire', 'Axe', 2.0, 2.0, True, True, '1.14'),
    ('jukebox', 'Jukebox', 'Axe', 2.0, 6.0, False, True, 'Indev–Beta'),
    ('note_block', 'Note Block', 'Axe', 0.8, 0.8, False, True, 'Indev–Beta'),
    ('scaffolding', 'Scaffolding', 'Axe', 0.0, 0.0, True, True, '1.14'),
    ('ladder', 'Ladder', 'Axe', 0.4, 0.4, True, True, 'Indev–Beta'),
    ('lectern', 'Lectern', 'Axe', 2.5, 2.5, False, True, '1.14'),
    ('spawner', 'Monster Spawner', 'Pickaxe', 5.0, 5.0, True, False, 'Indev–Beta'),
    ('end_portal_frame', 'End Portal Frame', 'None', -1.0, 3600000.0, False, False, '1.0'),
    ('dragon_egg', 'Dragon Egg', 'Any', 3.0, 9.0, True, False, '1.0'),
    ('crafter', 'Crafter', 'Pickaxe', 1.5, 3.5, False, True, '1.21'),
    ('trial_spawner', 'Trial Spawner', 'Any', 50.0, 50.0, True, False, '1.21'),
    ('vault', 'Vault', 'Any', 50.0, 50.0, True, False, '1.21'),
    ('heavy_core', 'Heavy Core', 'Pickaxe', 10.0, 1200.0, False, False, '1.21'),
    ('decorated_pot', 'Decorated Pot', 'Any', 0.0, 0.0, True, True, '1.20'),
    ('suspicious_sand', 'Suspicious Sand', 'Shovel', 0.25, 0.25, False, False, '1.20'),
    ('sniffer_egg', 'Sniffer Egg', 'Any', 0.5, 0.5, True, False, '1.20'),
    ('redstone_lamp', 'Redstone Lamp', 'Any', 0.3, 0.3, False, True, '1.2'),
    ('piston', 'Piston', 'Pickaxe', 1.5, 1.5, False, True, 'Indev–Beta'),
    ('sticky_piston', 'Sticky Piston', 'Pickaxe', 1.5, 1.5, False, True, 'Indev–Beta'),
    ('observer', 'Observer', 'Pickaxe', 3.0, 3.0, False, True, '1.11'),
    ('dispenser', 'Dispenser', 'Pickaxe', 3.5, 3.5, False, True, 'Indev–Beta'),
    ('dropper', 'Dropper', 'Pickaxe', 3.5, 3.5, False, True, '1.5'),
    ('hopper', 'Hopper', 'Pickaxe', 3.0, 4.8, True, True, '1.5'),
    ('tnt', 'TNT', 'Any', 0.0, 0.0, False, True, 'Classic'),
    ('lever', 'Lever', 'Any', 0.5, 0.5, True, True, 'Indev–Beta'),
    ('stone_button', 'Stone Button', 'Pickaxe', 0.5, 0.5, True, True, 'Indev–Beta'),
    ('stone_pressure_plate', 'Stone Pressure Plate', 'Pickaxe', 0.5, 0.5, True, True, 'Indev–Beta'),
    ('redstone_torch', 'Redstone Torch', 'Any', 0.0, 0.0, True, True, 'Indev–Beta'),
    ('repeater', 'Redstone Repeater', 'Any', 0.0, 0.0, False, True, 'Indev–Beta'),
    ('comparator', 'Redstone Comparator', 'Any', 0.0, 0.0, False, True, '1.5'),
    ('daylight_detector', 'Daylight Detector', 'Axe', 0.2, 0.2, False, True, '1.5'),
    ('lightning_rod', 'Lightning Rod', 'Pickaxe', 3.0, 6.0, True, True, '1.17'),
    ('tripwire_hook', 'Tripwire Hook', 'Any', 0.0, 0.0, True, True, '1.3'),
    ('rail', 'Rail', 'Pickaxe', 0.7, 0.7, True, True, 'Indev–Beta'),
    ('powered_rail', 'Powered Rail', 'Pickaxe', 0.7, 0.7, True, True, 'Indev–Beta'),
    ('iron_door', 'Iron Door', 'Pickaxe', 5.0, 5.0, True, True, 'Indev–Beta'),
    ('oak_door', 'Oak Door', 'Axe', 3.0, 3.0, True, True, 'Indev–Beta'),
    ('iron_trapdoor', 'Iron Trapdoor', 'Pickaxe', 5.0, 5.0, True, True, '1.8'),
    ('iron_bars', 'Iron Bars', 'Pickaxe', 5.0, 6.0, True, True, 'Indev–Beta'),
    ('chain', 'Chain', 'Pickaxe', 5.0, 6.0, True, True, '1.16'),
    ('glow_lichen', 'Glow Lichen', 'Axe', 0.2, 0.2, True, False, '1.17'),
)
